### ISSUE TITLE
The Triode should better filter unknown MIDI messages

### ISSUE THREAD

**Issue by samboy** [MeeBlip/meeblip-triode#1]
There is an issue reported by [a user on Reddit](https://www.reddit.com/r/synthesizers/comments/58phrq/filtering_out_midi_clock/) that the Meeblip Triode has issues receiving MIDI note on messages when receiving a number of presumably unknown MIDI messages, probably either MIDI [Song Position Pointer](http://www.recordingblogs.com/sa/Wiki/topic/MIDI-Song-Position-Pointer-message) or [MTC](https://en.wikipedia.org/wiki/MIDI_timecode) message.

Looking at [mini_in.inc](https://github.com/MeeBlip/meeblip-triode/blob/master/Firmware/midi_in.inc), as of commit c66a3ed, there is code between lines 23 and 29 which immediately removes the Triode from the interrupt caused by a MIDI message sent should it be a byte between F0 and FF. And, indeed, when my Triode gets a [MIDI Beat Clock](https://en.wikipedia.org/wiki/MIDI_beat_clock) message from my Korg ER-1 along with note-on commands, the Triode is able to play the notes without problem, since MIDI Beat Clock only consists of the bytes F8, FA, FB, and FC.

However, the Triode stops being able to respond to MIDI messages when getting more complicated unknown MIDI messages. Looking at mini_in.inc, the issue appears to be that, when MIDIPHASE (the byte of a MIDI message we are looking at) is 0, and an unknown byte is received, instead of immediately exiting from the MIDI interrupt, mini_in.inc compares the incoming byte and MIDIPHASE to a number of possible values before finally exiting the interrupt.

To resolve this, I propose adding two instructions right after the INTRX_DATA jump point, on line 73 of the current version of midi_in.inc, like this:

```
INTRX_DATA:
 lds r17, MIDIPHASE ; This is already here on line 73
 cpi r17, 0 ; On the old 6502, this isn't needed 
 breq INTRX_ACPT_X ; Which will jump us to INTRX_EXIT
 cpi r17, 0x80 ; This is in the current code; go on as the current code does
```

Thoughts? This fix should make the Triode more useful when slaved to devices which send complex MIDI data when sending out a clock signal over MIDI.

Edit: Looking at the code again, INTRX_ACPT_X is close enough to this that we can call that with [BREQ](http://www.atmel.com/webdoc/avrassembler/avrassembler.wb_BREQ.html)

**Comment by jgrahame** [comment]
Will implement and test.

**Comment by jgrahame** [comment]
Hi Sam -

Thanks for the message. Will have to do a careful walkthrough to be sure,
but this might sort the issue out. Will try it later this weekend and let
you know how things go.

**Comment by jgrahame** [comment]
Implemented change. Tested extensively and couldn't get it to fail. Online comments suggest Elektron is doing something unusual with the Octatrack MIDI clock output. Will investigate with their hardware.

**Comment by jgrahame** [comment]
Hey sam -

After feedback from users...

We'll be releasing V1.1 of the firmware next week, which has MIDI 
improvements, better filter behaviour (especially low), better 
enveloping and some voicing improvements as well. It's a significant 
upgrade that makes a big difference to the instrument's sound.

The upgrade will be available as a replacement chip or download for 
people who own AVR programmers. More details soon!

James Grahame

**Comment by samboy** [comment]
How much will a replacement ATmega chip for the Triode with the updated firmware cost, and how can one go about ordering one?

— Sam (I prefer the chip solution, because, over the long term, it’s more sustainable)
