### ISSUE TITLE
Midi CC for Sub-Oscillator level (volume)

### ISSUE THREAD

**Issue by oO** [MeeBlip/meeblip-triode#4]
Looking at the code, (not an Assembly programmer, so it reads, very very slowly) it seems possible to support control of the sub-oscillator level from Midi CC (I guess a mult rather than a if somewhere?) . I would change the way the CC#64 works by using the full range 0-127 for volume, instead of on/off at >=64. You can still have full bypass of the sub calculation at level = 0

Also is the sub-oscillator 1 or 2 octaves down? This is orthogonal from the Midi CC question, but since your switches have 2 states, you could actually have the sub function as Off/-1/-2

**Comment by jgrahame** [comment]
The sub-osc output is mixed with the main oscillators as an analog signal. There is no control of amplitude.
