### ISSUE TITLE
panic button for hung notes

### ISSUE THREAD

**Issue by oO-Zam** [MeeBlip/meeblip-triode#8]
I'm getting a lot of stuck notes and missed midi events from my MeeBlip when driving it from the Squarp Pyramid. It would be great to have the midi button stop all open notes when pressed ( or whatever scheme would allow me to have a quick "panic button" to use.

Alternativelly, supporting the "AllNotesOff" midi message would also be great.

**Comment by jgrahame** [comment]
We'll be releasing a firmware update later this week that uses significantly fewer processor cycles, would be great if you could test that with the Pyramid.

**Comment by oO-Zam** [comment]
Will do. Still think turning the button into a panic button would be great. You can double up with the Midi setting, since you probably want to stop all notes when switching channels.

**Comment by jgrahame** [comment]
Version 1.20 fixes issues with MIDI clock and hung notes.
